---
format: docx
---

Cytometry in R: A free weekly mini-course for coding beginners.

David Rach1,2, Natarajan Ayithan2, Xiaoxuan Fan2 1 Molecular Microbiology and Immunology Graduate Program, University of Maryland School of Medicine, Baltimore, USA 2 Flow Cytometry Shared Resource, University of Maryland Greenebaum Comprehensive Cancer Center, Baltimore, USA

As spectral flow cytometry (SFC) panels grow larger, thoroughly analyzing the resulting datasets becomes increasingly complicated. Unlike conventional flow and mass cytometry panels, SFC datasets contain both substantial number of markers and cells. While this makes them suitable for profiling heterogeneity in rare cell subsets, discovery of unknown cell populations within this higher-dimensional space remains a challenge. Consequently, if the goal is not to analyze a single cell subset, but all cell populations present in a sample, semi-supervised and unsupervised methods of analysis will be needed. Within our field, many of these cutting edge tools and algorthmic methods are implemented as R packages. 

While cytometry enthusiast often express an interest in learning how use R, several barriers to learning how exist. If not already at an instution with existing computational cytometry expertise, the question is often where to start. As the few existing online resources are primarily aimed at those with intermediate bioinformatic skills, self-study attempts often end in frustration due to lack of beginner suitable materials and troubleshooting support. 

To address this community need, we have been offering a free weekly 'Cytometry in R' mini-course, aimed at those with prior flow cytometry experience, but no-to-little coding experience. The course covers one topic each week, and is offered both in-person and online via a YouTube livestream, with recordings made available immediately afterwards (https://www.youtube.com/@CytometryInR). The course covers one topic each week, with all code and course materials being available via a GitHub repository and website (https://umgcccfcsr.github.io/CytometryInR/). In our commitment to open-science, all teaching materials are licensed under CC-BY-SA, with the code being made available under the copyleft AGPL3-0 license. In addition, a discussion forum is run so that course participants can get help, ask questions, and explore topics further. 

The course was advertised starting in November and December 2025 on the Cytometry Discord, r/flowcytometry Reddit, LinkedIn and the Purdue list. We received outstanding community interest, with over 1988 individuals ultimately completing the interest form. Using various metrics (Google Analytics, YouTube views, GitHub fork updates) around 500 participants have started the course, with between 250 and 350 active weekly participants. The course has been well received, and we continue to learn, respond to feedback, and adjust as we go. 

The course is comprehensive, with over 30 weeks of topics planned, intended to provide beginners solid foundations in R before moving on to intermediate and advanced cytometry topics as their coding skills and troubleshooting expertise develops. As all recordings and teaching materials will remain freely available after course completion, we hope to significantly reduce the existing barriers to analyzing Cytometry data in R, permitting anyone who starts their own self-study journey in the future has a smoother journey than the one we ourselves experienced when first getting started. 