---
title: "QR Codes"
format: html
---


This page was used to generate the QR codes needed for our Cyto 2026 poster using the `qrcode` R package. 

```{r}
library(qrcode)
```


# Helper Function

```{r}
QR_Helper <- function(url, output, filename){

code <- qr_code(url)

TheFileName  <- paste0(filename, ".svg")

StoreHere <- file.path(output, TheFileName)

generate_svg(code, filename = StoreHere)
#plot(code)
}
```

# Homepage

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/",
    output="outputs", 
    filename="Homepage")
```

# Schedule

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/Schedule.html",
    output="outputs", 
    filename="Schedule")
```

# UsingGitHub

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/00_GitHub/",
    output="outputs", 
    filename="UsingGithub")
```

# Installing R Packages

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/01_InstallingRPackages/",
    output="outputs", 
    filename="InstallingRPackages")
```

# FilePaths

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/02_FilePaths/",
    output="outputs", 
    filename="FilePaths")
```

# InsideFCSFile

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/03_InsideFCSFile/",
    output="outputs", 
    filename="InsideFCSFile")
```

# IntroTidyverse

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/04_IntroToTidyverse/",
    output="outputs", 
    filename="IntroTidyverse")
```

# GatingSets

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/05_GatingSets/",
    output="outputs", 
    filename="GatingSets")
```

# Visualizing_ggplot2

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/06_Visualizing/",
    output="outputs", 
    filename="Visualizing_ggplot2")
```

# Transformations

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/07_Transformations/",
    output="outputs", 
    filename="Transformations")
```

# WaysToGate

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/08_WaysToGate/",
    output="outputs", 
    filename="WaysToGate")
```

# RainingFunctions

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/09_Functions/",
    output="outputs", 
    filename="RainingFunctions")
```

# Downsampling

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/10_Downsampling/",
    output="outputs", 
    filename="Downsampling")
```

# DataForStats

```{r}
QR_Helper(url="https://umgcccfcsr.github.io/CytometryInR/course/11_DataForStats/",
    output="outputs", 
    filename="DataForStats")
```




